-- ============================================================================
-- SUPABASE DATABASE INITIALIZATION
-- ============================================================================
-- This script initializes the Supabase database with required schemas,
-- extensions, and tables for the Farmers Boot application.
-- ============================================================================

-- Ensure the internal role expected by Supabase exists so init scripts
-- do not fail when run in a fresh cluster.
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'supabase_admin') THEN
        CREATE ROLE supabase_admin;
    END IF;
END;
$$;

-- allow execution of pg_read_file from init scripts; image uses this to
-- inspect extension custom scripts and sometimes the default role lacks exec
GRANT EXECUTE ON FUNCTION pg_read_file(text) TO postgres;

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "pg_stat_statements";

-- ============================================================================
-- SCHEMAS
-- ============================================================================

-- Create storage schema for Supabase Storage
CREATE SCHEMA IF NOT EXISTS storage;
COMMENT ON SCHEMA storage IS 'Supabase Storage schema';

-- Create graphql_public schema for GraphQL
CREATE SCHEMA IF NOT EXISTS graphql_public;
COMMENT ON SCHEMA graphql_public IS 'GraphQL public schema';

-- Create extensions schema
CREATE SCHEMA IF NOT EXISTS extensions;
COMMENT ON SCHEMA extensions IS 'Extensions schema';

-- Create auth schema (if not exists, Supabase creates it)
CREATE SCHEMA IF NOT EXISTS auth;
COMMENT ON SCHEMA auth IS 'Supabase Auth schema';

-- Create realtime schema
CREATE SCHEMA IF NOT EXISTS realtime;
COMMENT ON SCHEMA realtime IS 'Supabase Realtime schema';

-- ============================================================================
-- STORAGE SCHEMA SETUP
-- ============================================================================

-- Storage tables
CREATE TABLE IF NOT EXISTS storage.buckets (
    id text NOT NULL,
    name text NOT NULL,
    owner uuid,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    public boolean DEFAULT false NOT NULL,
    file_size_limit bigint,
    allowed_mime_types text[],
    CONSTRAINT buckets_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS storage.objects (
    id uuid DEFAULT uuid_generate_v4() NOT NULL,
    bucket_id text NOT NULL,
    name text NOT NULL,
    owner uuid,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    last_accessed_at timestamp with time zone,
    metadata jsonb DEFAULT '{}'::jsonb,
    size bigint,
    hash text,
    path_tokens text[] NOT NULL,
    version text,
    CONSTRAINT objects_pkey PRIMARY KEY (id),
    CONSTRAINT objects_bucket_id_fkey FOREIGN KEY (bucket_id) REFERENCES storage.buckets(id) ON DELETE CASCADE
);

-- Storage indexes
CREATE INDEX IF NOT EXISTS objects_bucket_id_idx ON storage.objects(bucket_id);
CREATE INDEX IF NOT EXISTS objects_name_idx ON storage.objects(name);
CREATE INDEX IF NOT EXISTS objects_path_tokens_idx ON storage.objects USING GIN (path_tokens);

-- ============================================================================
-- GRANT PERMISSIONS
-- ============================================================================

GRANT USAGE ON SCHEMA storage TO postgres;
GRANT ALL ON storage.buckets TO postgres;
GRANT ALL ON storage.objects TO postgres;

GRANT USAGE ON SCHEMA public TO postgres;
GRANT USAGE ON SCHEMA auth TO postgres;
GRANT USAGE ON SCHEMA realtime TO postgres;
GRANT USAGE ON SCHEMA extensions TO postgres;

-- ============================================================================
-- REALTIME SCHEMA SETUP
-- ============================================================================

-- Realtime tables
CREATE TABLE IF NOT EXISTS realtime.messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic text NOT NULL,
    payload jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    extensions jsonb DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS realtime.topics (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic text NOT NULL UNIQUE,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Realtime indexes
CREATE INDEX IF NOT EXISTS realtime_messages_topic_idx ON realtime.messages(topic);
CREATE INDEX IF NOT EXISTS realtime_messages_created_at_idx ON realtime.messages(created_at DESC);

-- ============================================================================
-- FUNCTIONS
-- ============================================================================

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION storage.updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Triggers for updated_at
CREATE TRIGGER set_storage_buckets_updated_at BEFORE UPDATE ON storage.buckets
    FOR EACH ROW EXECUTE FUNCTION storage.updated_at_column();

CREATE TRIGGER set_storage_objects_updated_at BEFORE UPDATE ON storage.objects
    FOR EACH ROW EXECUTE FUNCTION storage.updated_at_column();

-- ============================================================================
-- INITIAL DATA
-- ============================================================================

-- Create default storage buckets
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES
    ('avatars', 'avatars', true, 5242880, ARRAY['image/jpeg', 'image/png', 'image/gif', 'image/webp']),
    ('documents', 'documents', false, 10485760, ARRAY['application/pdf', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document']),
    ('images', 'images', true, 10485760, ARRAY['image/jpeg', 'image/png', 'image/gif', 'image/webp', 'image/svg+xml']),
    ('videos', 'videos', true, 104857600, ARRAY['video/mp4', 'video/webm', 'video/quicktime'])
ON CONFLICT (id) DO NOTHING;
