packages:
  - 'apps/*'
  - 'packages/*'
overrides:
  dompurify: 3.4.11
  brace-expansion@1.1.12: 1.1.13
  brace-expansion@2.0.2: 2.0.3
  zod: 4.4.3
  '@supabase/realtime-js>ws': ^8.20.1
  exceljs>tmp: ^0.2.6
  exceljs>uuid: ^11.1.1
  svix>uuid: ^11.1.1
peerDependencyRules:
  ignoreMissing:
    - eslint
allowBuilds:
  core-js: set this to true or false
  esbuild: set this to true or false
  snyk: set this to true or false
onlyBuiltDependencies:
  - core-js
  - esbuild
  - snyk
